export const FETCHING_DATA = "FETCHING_DATA";
export const FETCHING_DATA_SUCCESS = "FETCHING_DATA_SUCCESS";
export const FETCHING_DATA_FAILURE = "FETCHING_DATA_FAILURE";
export const LIST_ITEM_SELECTED = "LIST_ITEM_SELECTED";
export const INCREMENT = "INCREMENT";
export const UPDATE_DIKR = "UPDATE_DIKR";
export const UPDATE_DIKR_COUNT = "UPDATE_DIKR_COUNT";
